# Generated by Django 5.2.4 on 2025-07-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('both', 'Both'), ('other', 'Other')], max_length=20)),
                ('collab_type', models.CharField(choices=[('barter', 'Barter'), ('paid', 'Paid'), ('gifting', 'Gifting'), ('affiliate', 'Affiliate')], max_length=20)),
                ('status', models.CharField(choices=[('contacted', 'Contacted'), ('no_reply', 'No Reply'), ('in_talks', 'In Talks'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('paid', 'Paid')], default='contacted', max_length=20)),
                ('pitch_date', models.DateField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('delivery_deadline', models.DateField(blank=True, null=True)),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='core.brand')),
            ],
        ),
    ]
