# Generated by Django 5.2.4 on 2025-07-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collaboration_barter_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='payment_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
