# Generated by Django 5.2.4 on 2025-07-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brand_description_brand_logo_brand_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='collab_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('barter', 'Barter'), ('gifting', 'Gifting'), ('affiliate', 'Affiliate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('no_reply', 'No Reply'), ('in_talks', 'In Talks'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='contacted', max_length=20),
        ),
    ]
